apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-1-deployment
  namespace: mlops
  labels:
    app: model-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-1
  template:
    metadata:
      labels:
        app: model-1
    spec:
      containers:
      - name: model-1-pod
        image: mlops1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: model-1-service
  namespace: mlops
  labels:
    app: model-1
spec:
  type: NodePort
  selector:
    app: model-1
  ports:
  - port: 5000
    targetPort: 5000
    name: model-1-port
