apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model-deployment
  namespace: mlops
  labels:
    app: ml-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
      - name: ml-model
        image: mlops1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-model-api
  namespace: mlops
  labels:
    app: model-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-api
  template:
    metadata:
      labels:
        app: model-api
    spec:
      containers:
      - name: api-model-cont
        image: mlops2
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ml-model-entrypoint
  namespace: mlops
  labels:
    app: ml-model
spec:
  type: NodePort
  selector:
    app: ml-model
  ports:
  - port: 5000
    targetPort: 5000
    name: model1-port
---
apiVersion: v1
kind: Service
metadata:
  name: model-service
  namespace: mlops
  labels:
    app: model-service
spec:
  type: NodePort
  selector:
    app: model-api
  ports:
  - port: 5000
    targetPort: 5000
    name: model2-port
