apiVersion: v1
kind: Service
metadata:
  name: master-api
  labels:
    app: master-api
spec:
  clusterIP: 10.96.1.10
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: master-api