FROM continuumio/anaconda3

COPY api.py .
COPY model.pkl .
COPY requirements.txt requirements.txt

RUN conda config --add channels conda-forge
RUN conda env create --name virtual-env --file requirements.txt python=3.9

ENTRYPOINT [ "conda", "run", "-n", "virtual-env", "--no-capture-output", "flask", "--app", "api.py", "run", "--host=0.0.0.0", "--port=8000"]