FROM continuumio/anaconda3

COPY api.py .
COPY model.pkl .
COPY requirements.txt requirements.txt

RUN conda env create --name virtual-env --file requirements.txt python=3.9

ENTRYPOINT [ "conda", "run", "-n", "virtual-env", "--no-capture-output", "python", "api.py" ]
