apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: model-ingress
spec:
  rules:
  - host: localhost
    http:
      paths: 
      - path: /rf
        pathType: Prefix
        backend:
          service:
            name: model-service
            port:
              number: 80  