name: terraform_4

on:
  push:
    branches: [ "feature/terraform_4" ]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: ./tasks/03_terraform_fundamentals/solution_4
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check -recursive

    - name: Terraform Plan
      run: terraform plan -input=false -var-file=${{ secrets.gcp_service_account_credentials}}

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false -var-file=${{ secrets.gcp_service_account_credentials}}